[2024-03-03T17:00:28.420+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aaexample_3.fetch_data_task manual__2024-03-03T17:00:27.160849+00:00 [queued]>
[2024-03-03T17:00:28.429+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aaexample_3.fetch_data_task manual__2024-03-03T17:00:27.160849+00:00 [queued]>
[2024-03-03T17:00:28.429+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-03T17:00:28.444+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_task> on 2024-03-03 17:00:27.160849+00:00
[2024-03-03T17:00:28.451+0000] {standard_task_runner.py:60} INFO - Started process 4885 to run task
[2024-03-03T17:00:28.455+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'aaexample_3', 'fetch_data_task', 'manual__2024-03-03T17:00:27.160849+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_tiga.py', '--cfg-path', '/tmp/tmpx1k2x5tv']
[2024-03-03T17:00:28.461+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask fetch_data_task
[2024-03-03T17:00:28.504+0000] {task_command.py:423} INFO - Running <TaskInstance: aaexample_3.fetch_data_task manual__2024-03-03T17:00:27.160849+00:00 [running]> on host 749678136a31
[2024-03-03T17:00:28.588+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aaexample_3' AIRFLOW_CTX_TASK_ID='fetch_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-03T17:00:27.160849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-03T17:00:27.160849+00:00'
[2024-03-03T17:00:28.591+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-03T17:00:31.730+0000] {logging_mixin.py:188} INFO -    id_transaksi  ...                 updated_at
0             1  ... 2024-02-27 10:24:21.937107
1             2  ... 2024-02-27 10:24:46.362615
2             3  ... 2024-02-27 10:24:46.362615
3             4  ... 2024-02-27 10:24:46.362615
4             5  ... 2024-02-27 10:24:46.362615
5             6  ... 2024-02-27 10:24:46.362615
6             7  ... 2024-02-27 10:24:46.362615
7             8  ... 2024-02-27 10:24:46.362615
8             9  ... 2024-02-27 10:24:46.362615
9            10  ... 2024-02-27 10:24:46.362615

[10 rows x 8 columns]
[2024-03-03T17:00:31.736+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-03T17:00:31.744+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=aaexample_3, task_id=fetch_data_task, execution_date=20240303T170027, start_date=20240303T170028, end_date=20240303T170031
[2024-03-03T17:00:31.798+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-03T17:00:31.822+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
