[2024-03-15T08:31:32.453+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:31:31.285689+00:00 [queued]>
[2024-03-15T08:31:32.460+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:31:31.285689+00:00 [queued]>
[2024-03-15T08:31:32.461+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-15T08:31:32.471+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): retrieve_data_and_save_to_csv> on 2024-03-15 08:31:31.285689+00:00
[2024-03-15T08:31:32.475+0000] {standard_task_runner.py:60} INFO - Started process 2156 to run task
[2024-03-15T08:31:32.479+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case1_restore', 'retrieve_data_and_save_to_csv', 'manual__2024-03-15T08:31:31.285689+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/restrore_mongo/study_case1_restore.py', '--cfg-path', '/tmp/tmpy0yjbjvq']
[2024-03-15T08:31:32.481+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask retrieve_data_and_save_to_csv
[2024-03-15T08:31:32.519+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:31:31.285689+00:00 [running]> on host f293363f8e27
[2024-03-15T08:31:32.582+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case1_restore' AIRFLOW_CTX_TASK_ID='retrieve_data_and_save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T08:31:31.285689+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-15T08:31:31.285689+00:00'
[2024-03-15T08:31:32.584+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-15T08:31:34.434+0000] {logging_mixin.py:188} INFO -                         _id  id  ... alamat         execution_at
0  65f4058125246f4b275642a8   1  ...    NaN  2024-03-15 15:23:19
1  65f4058125246f4b275642a9   2  ...    NaN  2024-03-15 15:23:19

[2 rows x 8 columns]
[2024-03-15T08:31:34.437+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-15T08:31:34.446+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=study_case1_restore, task_id=retrieve_data_and_save_to_csv, execution_date=20240315T083131, start_date=20240315T083132, end_date=20240315T083134
[2024-03-15T08:31:34.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-15T08:31:34.525+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
