[2024-03-12T18:09:02.560+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_tujuh.load_to_mongodb_task manual__2024-03-12T18:08:54.435701+00:00 [queued]>
[2024-03-12T18:09:02.569+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_tujuh.load_to_mongodb_task manual__2024-03-12T18:08:54.435701+00:00 [queued]>
[2024-03-12T18:09:02.569+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-12T18:09:02.580+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_to_mongodb_task> on 2024-03-12 18:08:54.435701+00:00
[2024-03-12T18:09:02.584+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-03-12T18:09:02.588+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_tujuh', 'load_to_mongodb_task', 'manual__2024-03-12T18:08:54.435701+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_tujuh.py', '--cfg-path', '/tmp/tmp4rd1usn_']
[2024-03-12T18:09:02.590+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask load_to_mongodb_task
[2024-03-12T18:09:02.626+0000] {task_command.py:423} INFO - Running <TaskInstance: example_tujuh.load_to_mongodb_task manual__2024-03-12T18:08:54.435701+00:00 [running]> on host 31e68e31498e
[2024-03-12T18:09:02.682+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_tujuh' AIRFLOW_CTX_TASK_ID='load_to_mongodb_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T18:08:54.435701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T18:08:54.435701+00:00'
[2024-03-12T18:09:02.683+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-12T18:09:02.694+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/other_ingestion_postgre/main_dag_sql_tujuh.py", line 58, in load_to_mongodb
    connection_string = Variable.get("MONGODB_CONNECTION_STRING")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable MONGODB_CONNECTION_STRING does not exist'
[2024-03-12T18:09:02.700+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=example_tujuh, task_id=load_to_mongodb_task, execution_date=20240312T180854, start_date=20240312T180902, end_date=20240312T180902
[2024-03-12T18:09:02.710+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 42 for task load_to_mongodb_task ('Variable MONGODB_CONNECTION_STRING does not exist'; 316)
[2024-03-12T18:09:02.724+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T18:09:02.741+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
