[2024-03-08T19:30:48.987+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_csv.retrieve_data_and_save_to_csv manual__2024-03-08T19:30:47.756534+00:00 [queued]>
[2024-03-08T19:30:48.997+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_csv.retrieve_data_and_save_to_csv manual__2024-03-08T19:30:47.756534+00:00 [queued]>
[2024-03-08T19:30:48.998+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-08T19:30:49.011+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): retrieve_data_and_save_to_csv> on 2024-03-08 19:30:47.756534+00:00
[2024-03-08T19:30:49.017+0000] {standard_task_runner.py:60} INFO - Started process 1277 to run task
[2024-03-08T19:30:49.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_csv', 'retrieve_data_and_save_to_csv', 'manual__2024-03-08T19:30:47.756534+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/restrore_mongo/main_dag_sql_lima.py', '--cfg-path', '/tmp/tmpw1jf4yuz']
[2024-03-08T19:30:49.024+0000] {standard_task_runner.py:88} INFO - Job 156: Subtask retrieve_data_and_save_to_csv
[2024-03-08T19:30:49.074+0000] {task_command.py:423} INFO - Running <TaskInstance: mongodb_to_csv.retrieve_data_and_save_to_csv manual__2024-03-08T19:30:47.756534+00:00 [running]> on host c9d1ac6dab48
[2024-03-08T19:30:49.147+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_csv' AIRFLOW_CTX_TASK_ID='retrieve_data_and_save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T19:30:47.756534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-08T19:30:47.756534+00:00'
[2024-03-08T19:30:49.149+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-08T19:30:49.158+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/restrore_mongo/main_dag_sql_lima.py", line 30, in retrieve_data_and_save_to_csv
    csv_file_path = f"{DATA_PATH}/{file_template}"
NameError: name 'file_template' is not defined
[2024-03-08T19:30:49.166+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_csv, task_id=retrieve_data_and_save_to_csv, execution_date=20240308T193047, start_date=20240308T193048, end_date=20240308T193049
[2024-03-08T19:30:49.179+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 156 for task retrieve_data_and_save_to_csv (name 'file_template' is not defined; 1277)
[2024-03-08T19:30:49.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-08T19:30:49.210+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
