[2024-03-07T16:38:19.056+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-07T16:38:17.953499+00:00 [queued]>
[2024-03-07T16:38:19.065+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-07T16:38:17.953499+00:00 [queued]>
[2024-03-07T16:38:19.066+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-07T16:38:19.077+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_task> on 2024-03-07 16:38:17.953499+00:00
[2024-03-07T16:38:19.082+0000] {standard_task_runner.py:60} INFO - Started process 790 to run task
[2024-03-07T16:38:19.085+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_lima_solid', 'fetch_data_task', 'manual__2024-03-07T16:38:17.953499+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_lima.py', '--cfg-path', '/tmp/tmpx1enn4e7']
[2024-03-07T16:38:19.087+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask fetch_data_task
[2024-03-07T16:38:19.125+0000] {task_command.py:423} INFO - Running <TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-07T16:38:17.953499+00:00 [running]> on host c9d1ac6dab48
[2024-03-07T16:38:19.182+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_lima_solid' AIRFLOW_CTX_TASK_ID='fetch_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T16:38:17.953499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T16:38:17.953499+00:00'
[2024-03-07T16:38:19.184+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-07T16:38:19.238+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/other_ingestion_postgre/main_dag_sql_lima.py", line 42, in fetch_data
    cursor = conn.cursor()
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-03-07T16:38:19.245+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=example_lima_solid, task_id=fetch_data_task, execution_date=20240307T163817, start_date=20240307T163819, end_date=20240307T163819
[2024-03-07T16:38:19.255+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task fetch_data_task ('Engine' object has no attribute 'cursor'; 790)
[2024-03-07T16:38:19.297+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-07T16:38:19.316+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
